stages:
- build
- publish-controller
- publish-operator

build:
  stage: build
  script:
  - make build


publish-controller:
  stage: publish-controller
  script:
  - make docker-buildx
  when: manual

publish-operator:
  stage: publish-operator
  script:
  - make prepare-build
  when: manual
