apiVersion: media.flussonic.com/v1alpha1
kind: Central
metadata:
  labels:
    app.kubernetes.io/name: central
    app.kubernetes.io/instance: central
    app.kubernetes.io/part-of: central-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: central-operator
    app: central
  name: central
spec:
  database:
    value: "postgresql://central:668bfadfd824@postgres:5432/central_db"
  redis:
    value: "redis://redis:6379"
  version: "v25.12-17"
  apiKey:
    valueFrom: 
      secretKeyRef:
        name: api-keys
        key: config-ext
        optional: false
  provisionerClusterKey: "clusterkey"
  provisionerSelector: "streamer"
  central:
    replicas: 2
    env:
      - name: CENTRAL_LICENSE_KEY
        valueFrom:
          secretKeyRef:
            name: license
            key: license_key
            optional: false
      - name: CENTRAL_EDIT_AUTH
        valueFrom:
          secretKeyRef:
            name: license
            key: edit_auth
            optional: false
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_LOG_REQUESTS
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: CENTRAL_LOG_REQUESTS
      - name: CENTRAL_STREAMER_DEAD_TIMEOUT
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: streamer_dead_timeout
  layouter:
    env:
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_STREAMER_DEAD_TIMEOUT
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: streamer_dead_timeout
  agentsUnit:
    env:
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_LOG_REQUESTS
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: CENTRAL_LOG_REQUESTS
  singletonUnit:
    env:
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_LOG_REQUESTS
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: CENTRAL_LOG_REQUESTS
