apiVersion: media.flussonic.com/v1alpha1
kind: Central
metadata:
  labels:
    app.kubernetes.io/name: central
    app.kubernetes.io/instance: central
    app.kubernetes.io/part-of: central-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: central-operator
    app: central
  name: central
  namespace: catena-se
spec:
  database:
    value: "postgresql://central:668bfadfd824@postgres:5432/central_db"
  redis:
    value: "redis://redis:6379"
  apiURL:
    value: "http://central.catena-se.svc.cluster.local"
  version: "v25.12-17"
  apiKey:
    value: "0877d9c6-f1f3-4070-a970-3e0e54c41c00"
  provisionerClusterKey: "clusterkey"
  provisionerSelector: "mediaserver-media-server"
  streamersConfigURLs:
    s1:
      apiUrl: http://s1-streamer-0.s1-headless.catena-se.svc.cluster.local:81
      privatePayloadUrl: http://s1-streamer-0.s1-headless.catena-se.svc.cluster.local:81
      publicPayloadUrl: https://s1.my-service.local
  central:
    replicas: 2
    env:
      - name: CENTRAL_LICENSE_KEY
        valueFrom:
          secretKeyRef:
            name: license
            key: license_key
            optional: false
      - name: CENTRAL_EDIT_AUTH
        valueFrom:
          secretKeyRef:
            name: license
            key: edit_auth
            optional: false
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_LOG_REQUESTS
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: CENTRAL_LOG_REQUESTS
      - name: CENTRAL_STREAMER_DEAD_TIMEOUT
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: streamer_dead_timeout
  layouter:
    env:
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_STREAMER_DEAD_TIMEOUT
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: streamer_dead_timeout
  agentsUnit:
    env:
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_LOG_REQUESTS
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: CENTRAL_LOG_REQUESTS
  singletonUnit:
    env:
      - name: CENTRAL_LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: log_level
      - name: CENTRAL_LOG_REQUESTS
        valueFrom:
          configMapKeyRef:
            name: central-config
            key: CENTRAL_LOG_REQUESTS
