apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "media.flussonic.com/v1alpha1",
          "kind": "MediaServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "media-server-operator",
              "app.kubernetes.io/instance": "mediaserver-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "mediaserver",
              "app.kubernetes.io/part-of": "media-server-operator"
            },
            "name": "watcher"
          },
          "spec": {
            "adminHostPort": 86,
            "configExtra": {
              "watcher.conf": "cluster_key FxNtj8tU0olsD1;\ndvr central {\n  root /storage;\n}\nauth_backend vsaas {\n  backend http://watcher.default.svc.cluster.local/vsaas/api/camera_auth;\n}\n"
            },
            "env": [
              {
                "name": "LICENSE_KEY",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "license_key",
                    "name": "flussonic-license",
                    "optional": false
                  }
                }
              },
              {
                "name": "FLUSSONIC_EDIT_AUTH",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "edit_auth",
                    "name": "flussonic-license",
                    "optional": false
                  }
                }
              }
            ],
            "hostPort": 85,
            "image": "flussonic/flussonic:v24.02-107",
            "nodeSelector": {
              "flussonic.com/streamer": "true"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-03-04T14:34:17Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: media-server-operator.v24.3.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MediaServer is the Schema for the mediaservers API
      displayName: Media Server
      kind: MediaServer
      name: mediaservers.media.flussonic.com
      version: v1alpha1
  description: Flussonic Media Server operator
  displayName: MediaServer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - media.flussonic.com
          resources:
          - mediaservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - media.flussonic.com
          resources:
          - mediaservers/finalizers
          verbs:
          - update
        - apiGroups:
          - media.flussonic.com
          resources:
          - mediaservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: media-server-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: media-server-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: media-server-operator
          control-plane: controller-manager
        name: media-server-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: flussonic/media-server-controller:24.3.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: media-server-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: media-server-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - video
  - livestreaming
  - rtmp
  - rtsp
  - hls
  - dash
  - webrtc
  links:
  - name: Media Server Operator
    url: https://media-server-operator.domain
  maintainers:
  - email: m.lapshin@flussonic.com
    name: Max Lapshin
  maturity: alpha
  provider:
    name: flussonic.com
    url: https://flussonic.com/media-server/
  version: 24.3.1
