# permissions for end users to edit mediaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mediaserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: media-server-operator
    app.kubernetes.io/part-of: media-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: mediaserver-editor-role
rules:
- apiGroups:
  - media.flussonic.com
  resources:
  - mediaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - media.flussonic.com
  resources:
  - mediaservers/status
  verbs:
  - get
